services:
  - type: web
    name: lumea-tm
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: admin@lumea.fr
      - key: ADMIN_PASSWORD
        value: lumea2026
